### ISSUE TITLE
Hardmode checklist

### ISSUE THREAD

**Issue by ThePansmith** [ThePansmith/Monifactory#170]
# Infra
- [x] Pack mode switching
- [x] Questbook switching

# Additions
- [ ] Universal Crystallizer (or work it's empowered and diamond recipes into another multi)
- [x] Steam age
- [ ] T4.5 MM (or, instead add missions to fitting preexisting MMs)
- [ ] [see expert_processing.zs](https://github.com/Nomi-CEu/Nomi-CEu/blob/main/overrides/scripts/expert_processing.zs)
- [ ] [see multiblocks_expert.zs](https://github.com/Nomi-CEu/Nomi-CEu/blob/main/overrides/scripts/multiblocks_expert.zs)

# Recipe Nerfs
- [x] [see expertmode.zs](https://github.com/Nomi-CEu/Nomi-CEu/blob/main/overrides/scripts/expertmode.zs)

# Recipe removals
- [x] Monicoins, recipes disabled
- [x] Most everything related to HNN
- [x] [see expertmode.zs](https://github.com/Nomi-CEu/Nomi-CEu/blob/main/overrides/scripts/expertmode.zs)

# Misc thoughts

- Could lean into GT power even harder and disable converters
  - Harder Mode?

**Comment by WithersChat** [comment]
Idea: lean into GT power more in Normal mode (keep the converters, just less FE gen), and make hard mode not have the converters?

**Comment by ThePansmith** [comment]
Separating this into its own issues
