### ISSUE TITLE
NFM issues that are still on Moni

### ISSUE THREAD

**Issue by JuiceyBeans** [ThePansmith/Monifactory#38]
- [x] ~~Add Ender Lilies to the Insolator (#81)~~ Mini utilities was removed
- [x] Add facade crafting recipe to EMI
- [x] Cleaning impure dusts in a cauldron doesn't work (this could be a GTM bug to be fair)
- [x] Replace JEI with EMI in quests (#68)
- [ ] Hypochlorous acid quest (Microverse chapter) uses the same description as the ammonia quest (WIP #28)
- [x] A lot of mid game chapter liquid quests requires liquid instead of bucket of liquid, making them incompletable
- [x] Pulsating Polymer Clay texture uses prediction matrix texture from HNN (#1)

**Comment by WithersChat** [comment]
#126 makes only the Infinity Block AE2 facade visible in EMI, with a tooltip that says "Crafted with Cable Anchors"
